- name: 显示facts
  debug:
    msg: '{{ init_mysql }}'
    #msg: '{{ ansible_facts["os_family"]|lower }}'

# 我们使用 include_tasks 导入具体安装任务
- name: 安装 MySQL on redhat
  include_tasks: redhat.yml
  when:
    - ansible_facts['os_family']|lower == 'redhat'
    - "init_mysql  == True"

- name: 安装 MySQL on debian
  include_tasks: debian.yml
  when:
    - ansible_facts['os_family']|lower == 'debian'
    - "init_mysql  == True"


- name: 启动 MySQL for redhat
  service:
    name: mariadb
  when:
    - ansible_facts['os_family']|lower == 'redhat'
    - "init_mysql  == True"
